### PR TITLE
gaming

### PR DESCRIPTION
**Pull request by GitHubUser53123**
## About the PR
buff mining, add basic ore processor, add circuit imprinter to autolathe, add a new shuttle event

## Why / Balance
mining feels unrewarding and shit to me, and a new shuttle event because funny

## Breaking changes

**Changelog**

- add: Added Basic Ore Processor circuitboard to the Autolathe. 
- add: Added Circuit Imprinter to the Autolathe.
- add: Added a new shuttle event, Trambullet class Engineering Failure.
- tweak: Buffed mining.

### CODE REVIEW

**Review by Merrokitsune — DISMISSED** [review]
Arbitrage error needs to be fixed.

**Comment by GitHubUser53123** [comment]
image - 2024-11-18T205841 343
the engineering failure shuttle, related to PR

**Comment by GitHubUser53123** [comment]
^^^ lacks tiny fans that i placed in the last version of the shuttle

**Comment by GitHubUser53123** [comment]
all checks passed, you can merge now

**Comment by Merrokitsune** [comment]
Right, so be it.

**Review by Merrokitsune — COMMENTED** [review]
POST-MERGE: it's fine.

**Pull request merged**
