### PR TITLE
Demexatrine

### PR DESCRIPTION
**Pull request by FlapstheMoth**
## About PR
Demexatrine, this chem will be given to salvagers as a (space) medipen for fast and accessible first aid, but will overdose if given too much of it.
## Why / Plans
Gives some purpose to Epinephrine, will be expanded on further and will be given much more usage later on.

### CODE REVIEW

**Comment by FlapstheMoth** [comment]
still wondering why it's failing

**Comment by FlapstheMoth** [comment]
done :3

**Comment by Merrokitsune** [comment]
> done :3 ready for review

I’m not sure if this a good change, or just mere bloat, as the space medipen can already do the job.

**Comment by Merrokitsune** [comment]
Post-closing, consensus from administrators is to deny the Demexatrine. No player feedback has been provided, so only administrator feedback has been taken account into.

Thank you for your contribution.

**Pull request closed without merging**
