### PR TITLE
goliath rebalance

### PR DESCRIPTION
**Pull request by GitHubUser53123**
## About the PR
goliath hp 250 -> 175
goliath stun duration 5 -> 2
goliath dmg 20 (10/10) -> 12 (6/6)
goliath vision radius 6 -> 8
goliath aggro radius 10 -> 12
goliath tentacle range 10 -> 12
goliath tentacle cooldown 8 -> 4
adds a gauze to salvage lockers to help fighting against hivelords

## Why / Balance
makes fighting against goliaths actually viable and not a somewhat suicide

## Media
rah

## Requirements
nun.

## Breaking changes
nun.
**Changelog**
Goliaths are now actually fun to fight against.

### CODE REVIEW

**Comment by Merrokitsune** [comment]
We only got like 1 salvagers every round, so why not.

**Comment by GitHubUser53123** [comment]
hello ronstation, i am your only player. all other accounts were my bots. ill respond from all other accounts.

**Comment by Merrokitsune** [comment]
> hello ronstation, i am your only player. all other accounts were my bots. ill respond from all other accounts.

Unfortunately, for you, that is a blatant lie. (Yes, I do get the joke)

**Comment by FlapstheMoth** [comment]
> hello ronstation, i am your only player. all other accounts were my bots. ill respond from all other accounts.

As one of GitHubUser53123 artificial intelligent machines, i am compelled to agree.

**Pull request merged**
