### PR TITLE
Substantial updates to Blueshield.

### PR DESCRIPTION
**Pull request by Merrokitsune**
## About the PR

- Gives blueshield new hats.
- Gives blueshield new backpacks.
- Gives blueshield new medal, accessible only for 100 hours as blueshield officer.
- Gives blueshield combat gloves and combat boots.
- Gives blueshield a disabler.
- Gives blueshield near-moderate access, as well as their own access.

## Why / Balance

Updates are needed to make the role fate better.

Might still update some more.

## Media

The new hats:
Screenshot from 2024-12-16 16-18-40

The new backpacks:
Screenshot from 2024-12-16 22-27-47

The new medal:
Screenshot from 2024-12-17 00-33-43

The centcom variant having a disabler:
Screenshot from 2024-12-16 16-28-06

The new access:
Screenshot from 2024-12-17 22-23-44

The blueshield locker(s):
Screenshot from 2024-12-17 20-28-18

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Blueshield gets new hats.
- add: Blueshield gets new backpacks.
- add: Blueshield gets new a new medal, accessible for playing as a blueshield officer long enough.
- tweak: Blueshield gets combat gloves and combat boots.
- add: Blueshield gets a disaler in a pocket.
- tweak: Blueshield gets near-moderate access.
- add: Blueshield gets their own access.

### CODE REVIEW

**Comment by Crime481** [comment]
what about my sprites and the new access though

**Comment by Merrokitsune** [comment]
> what about my sprites and the new access though

The medal will be incorporated as something among the lines of a blueshield version of security's dinky star, though recolored for consistency reasons.

Image:
Screenshot from 2024-12-16 21-21-08

I also have plans for a senior version.

**Comment by GitHubUser53123** [comment]
this is better than the pipebomb i expected

**Review by GitHubUser53123 — APPROVED** [review]

**Comment by GitHubUser53123** [comment]
good 2 merge?

**Comment by Crime481** [comment]
sure sure

**Comment by Merrokitsune** [comment]
> good 2 merge?

@GitHubUser53123, yes, you may.

**Comment by Merrokitsune** [comment]
*sighs.

I do not know what to do with this.

**Pull request closed without merging**
