### PR TITLE
Add TEG flatpacks and put them on the market.

### PR DESCRIPTION
**Pull request by Merrokitsune**
## About the PR

Adds TEG flatpacks, and associated circuitboards, and adds them to the cargo catalog.

## Why / Balance

Currently, the TEG is the only power generator, besides the infinite power generators, that you cannot build or deconstruct, which is rather odd.
This PR was made because 1 user requested that this be made.

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added TEG flatpacks, and associated circuitboards, and adds them to the cargo catalog.

### CODE REVIEW

**Comment by Merrokitsune** [comment]
Opening it up.

**Comment by GitHubUser53123** [comment]
Error: /Prototypes/Ronstation/Entities/Objects/Devices/Circuitboards/engines.yml(10,5)

**Comment by Merrokitsune** [comment]
Ah, I forgot. Will resolve later. Right now, I’ll put a “Do not merge” label until it’s fixed.

**Comment by Merrokitsune** [comment]
@GitHubUser53123, it should be able to be merged now.

**Comment by GitHubUser53123** [comment]
looks good

**Pull request merged**
