### PR TITLE
new chems part four

### PR DESCRIPTION
**Pull request by FlapstheMoth**
## About the PR
Fun first, boring part _(moving newchem to ronstation folder)_ last.

## Why / Balance
Ports some chems and gives more taste to chemistry, fun.

- [x] Morphine
- [x] Opium
- [x] Stabilizing agent
- [x] Libital
- [ ] Salicyclic Acid
- [ ] Salbutamol
- [ ] Coffee metabolises into Caffeine
- [ ] Bromine (included in chemical dispensers)
- [ ] Calcium (included in chemical dispensers)
- [ ] Platinum (included in chemical dispensers)
- [ ] Barium (included in chemical dispensers)
- [ ] Helium (included in chemical dispensers)
- [ ] Magnesium (included in chemical dispensers)

### CODE REVIEW

**Comment by FlapstheMoth** [comment]
fix shit l8r, don't merge yet

**Comment by FlapstheMoth** [comment]
> epic check fail

Smite the shitcode :point_up:

**Comment by Merrokitsune** [comment]
> fix shit l8r, don't merge yet

Added a label. In case you want to remove the label after you’re finished, do tell me.

**Comment by FlapstheMoth** [comment]
will make better version of this soon, just need motivation

**Pull request closed without merging**
