### PR TITLE
More chemistry

### PR DESCRIPTION
**Pull request by FlapstheMoth**
## About the PR
Addon of #147, fixes some mistakes previously made

### CODE REVIEW

**Comment by Merrokitsune** [comment]
IMG_6022
I am not able to find the source of the error, unfortunately.

**Comment by FlapstheMoth** [comment]
> IMG_6022 I am not able to find the source of the error, unfortunately.

oneof my reactions has a invalid recipe, probably cyanide or glycerol

**Comment by FlapstheMoth** [comment]
Glycerol and PlasticSheet confound with eachother, after i change the recipe for glycerol it's gonna be fixed

**Comment by FlapstheMoth** [comment]
Based

**Review by Merrokitsune — APPROVED** [review]
I applaud the lots of work you’ve put into.

**Pull request merged**
