### PR TITLE
base point source in cargo, orderable rnd servers, autolathe/protolathe/circuitimprinter flatpacks at cargo

### PR DESCRIPTION
**Pull request by GitHubUser53123**
## About the PR
added
5k disk in cargo (3k)
added protolathe/autolathe/circuit imprinter flatpacks (8k each)
added rnd server (30k)
added base point source (15k, points per second nerfed to 10)

## Why / Balance
funny
## Technical details
nun
## Media
nun
## Requirements
nun
## Breaking changes
nun

**Changelog**
More science stuff can be ordered at Cargo.

### CODE REVIEW

**Comment by GitHubUser53123** [comment]
wait FUCK whats up with teh checks fails

**Comment by GitHubUser53123** [comment]
all check passed yipee lets go

**Comment by GitHubUser53123** [comment]
wait fucking RAHHH i forgot to move it to ron folders

**Comment by GitHubUser53123** [comment]
one check still successfuln't wtf

**Comment by GitHubUser53123** [comment]
might be a general issue, another PR catched same check fail

**Comment by Merrokitsune** [comment]
Frozen due to update incoming.
You are still able to work on your PR.

**Comment by Merrokitsune** [comment]
Unfrozen.

**Comment by Merrokitsune** [comment]
Consensus seems to lean to approval. Merging shall be done.

**Pull request merged**
