### PR TITLE
Space Mushroom changes

### PR DESCRIPTION
**Pull request by FlapstheMoth**
## About the PR
Adds several new chemicals that are found in space mushrooms, changes sprites, they will not be removed entirely from the station and the mushrooms will still be found in maintenance tunnels.

## Notes
Preparing for "native people" of the salvage meteor (probably golems) as an uncommon midround antag that can be found in the meteor and meteor only, salvage is quite unappealing in it's current form due to having absolutely no real dangers or any flora or fauna except Hivelords and Goliaths, all of this information will be soon written into a google document or something

### CODE REVIEW

**Comment by FlapstheMoth** [comment]
ready for review, done

**Review by Merrokitsune — CHANGES_REQUESTED** [review]
Hey, @FlapstheMoth. Can you please provide the source of where the new mushroom sprites are from in the meta.json?

**Comment by FlapstheMoth** [comment]
> Hey, @FlapstheMoth. Can you please provide the source of where the new mushroom sprites are from in the meta.json?

https://www.paradisestation.org/wiki/index.php?title=File:Nmushrooms.png

**Comment by Merrokitsune** [comment]
> > Hey, @FlapstheMoth. Can you please provide the source of where the new mushroom sprites are from in the meta.json?
> 
> https://www.paradisestation.org/wiki/index.php?title=File:Nmushrooms.png , item sprite is made by me

Did a little dig, and found that the sprites are added by TGstation in commit https://github.com/tgstation/tgstation/pull/20411/commits/8533cb12ed8b57d2992a6113f6b09133ba72c5ae

So, right now, I am requesting that the following changes be made to the spaceshrooms’ meta.json.
1. The “license” part should be converted to CC-BY-SA-3.0.
2. The “copyright” part should be changed to “Taken from TGStation in commit https://github.com/tgstation/tgstation/pull/20411/commits/8533cb12ed8b57d2992a6113f6b09133ba72c5ae. Item sprites made by FlapstheMoth.”

**Review by Merrokitsune — APPROVED** [review]
This sounds good. Thank you for your contribution. This PR shall be merged.

**Pull request merged**
