### PR TITLE
Make firebots and janibots targets of sentience events.

### PR DESCRIPTION
**Pull request by Merrokitsune**
## About the PR

Makes firebots and janibots targets of sentience events.

## Why / Balance

When you got killed, the only choices you have are either immobile vending machines mostly locked away in departments from crew, pests that can't speak and get killed often, and station pets that are very often locked up in their respective departments (and can't speak), all unable to make meaningful interactions (and in turn, roleplay). Imagine, being a minor bot, not only becoming a spare 'silicon', but getting to actually help people. Does that sound fun to you?

## Media

Screenshot from 2024-10-26 00-54-24
Screenshot from 2024-10-26 21-37-58

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: Firebots and Janibots can become targets of sentience events.

### CODE REVIEW

**Comment by GitHubUser53123** [comment]
have you tested whenever they have respective functionality under player's control

**Comment by Merrokitsune** [comment]
Frozen, due to update.

**Comment by Merrokitsune** [comment]
Unfrozen.

**Comment by Merrokitsune** [comment]
> have you tested whenever they have respective functionality under player's control

Yes, I have.
And they seemed to work.
Janibots can clean, and firebots can spray. They can also seem to speak.
Screenshot from 2024-10-26 21-37-58

**Pull request merged**
