### PR TITLE
Added blueshield role.

### PR DESCRIPTION
**Pull request by Merrokitsune**
## About the PR

Adds blueshield role, protectors of head-of-staff. I also added blueshield role spawners on 3 of our maps: Saltern-II, Cluster-II, and Atlas-B.
They currently only have access to the bridge, as well as maintenance, external, and cryogenics.

## Why / Balance

Came from a suggestion. This should give command, as well as other VIPs like Central Commanders, dedicated bodyguards.

The Blueshield ghostrole may be made after this PR is merged.

## Media

Screenshot 2024-09-02 220504
Screenshot 2024-09-02 222945
Screenshot 2024-09-02 225633
Screenshot 2024-09-02 224109
Screenshot 2024-09-02 225325
Screenshot 2024-09-02 225404
Screenshot 2024-09-02 225546

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added blueshield role.

### CODE REVIEW

**Comment by GitHubUser53123** [comment]
unneeded for lowpop imo

**Comment by Merrokitsune** [comment]
> unneeded for lowpop imo

The only maps where I can add stuff are those made by ourselves. Otherwise, any changes made to the maps made in upstream might wipe out our changes.

**Comment by GitHubUser53123** [comment]
> The only maps where I can add stuff are those made by ourselves. Otherwise, any changes made to the maps made in upstream > might wipe out our changes.
cant you just make a copy of the map and name it "something something II"

**Comment by GitHubUser53123** [comment]
github is shitting itself i cant fix a typo

**Pull request merged**
